### PR TITLE
Started supporting "n months ago" and "n years ago"

### PR DESCRIPTION
**Pull request by Saurabh3333**

### CODE REVIEW

**Comment by icyflame** [comment]
Hey, make sure Travis CI passes.

**Comment by Saurabh3333** [comment]
Sir, now I guess everything is good.

**Comment by icyflame** [comment]
Hey, thanks for your patch. Please rebase onto latest master, I have added tests for the particular case that you are trying to solve. These tests should pass.

**Comment by icyflame** [comment]
Closed in favor of #10

**Pull request closed without merging**
